### PR TITLE
Update to latest Vitepress and integrate twoslash

### PR DESCRIPTION
**Pull request by wycats**

### CODE REVIEW

**Comment by wycats** [comment]
Here's what it looks like:

twoslash

And dark mode:

twoslash-dark

There's still a bunch of polish because this change is big enough that it affects a lot of tangentially related things. I addressed the bulk of the regressions today but there's still a bit more to do.

**Comment by wycats** [comment]
And with the language switcher:

twoslash-with-switcher

**Comment by NullVoxPopuli** [comment]
looks like keyboard users can't focus any of these type / tooltip things :thinking:  :(

**Comment by NullVoxPopuli** [comment]
language switcher is keyboard-usable, am fan :100:

**Comment by wycats** [comment]
> language switcher is keyboard-usable, am fan 💯

That's what happens when you #JustUseAButton 😉 

To be totally honest, I didn't even think about making it keyboard usable, but it seems like using the recommended practices took care of it!

**Comment by wycats** [comment]
The biggest issue with the current status is that the JS version of TS/JS docs end up with a lot of `any`s for mechanical reasons.

I'm going to look into twoslash renderers to see if I can use information in the AST to tag type tokens so they can be targeted easily at runtime, but I don't want to wait for that to merge.

**Pull request merged**
