### PR TITLE
fix: References to React in Preact docs

### PR DESCRIPTION
**Pull request by rschristian**

### CODE REVIEW

**Comment by rschristian** [comment]
Apologies, I have no idea what the CI failure is -- apparently Vercel locks the status behind an auth wall and I'm not interested in signing up or connecting an account to them.

Let me know if it's something I need to correct.

**Review by NullVoxPopuli — APPROVED** [review]
Thanks for this! CI is likely unrelated to your changes

**Comment by wycats** [comment]
@rschristian I'm working on it!

**Comment by wycats** [comment]
For reference, the CI verifies that the types in the docs actually typecheck via twoslash (which generates the handy hoverable types in the docs), and for some reason, it's not working.

One thing that's been a bit tricky is having multiple kinds of JSX in the same repo and getting twoslash to find the right one, because twoslash's API requires you to specify a `cwd` for the entire project.

image

**Comment by wycats** [comment]
@NullVoxPopuli can we set up some normal CI that does `pnpm docs:build` so that vercel is not the only CI failure?

**Comment by wycats** [comment]
The change here shouldn't actually be necessary, because `@starbeam/preact` **should** support a dependency array here.

It doesn't in 0.8, and this example doesn't instantiate a resource with a stable Preact variable, so I updated the example to use the version of the API that doesn't need a dependency array.

fyi: Starbeam 0.9 should include a dependency array here.

**Pull request merged**
